name: On Tag Create Release

on:
  push:
    tags:
      # - "[0-9]+.[0-9]+.[0-9]+"
      - "*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV  # get date and save in environment variables, access with "${{ env.TODAY }}"

      - name: Create Release
        uses: actions/create-release@v1                                 # function that creates release, if fails with "Resource not accessible by integration": repository "Settings", "Actions", "General", "Workflow permissions", set "Read and write permissions", "Save"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                     # token is provided by Github Actions
        with:                                                           # parameters
          tag_name: ${{ github.ref }}                                   # release tag
          release_name: ${{ env.TODAY }} Metric METAR for Discord ${{ github.ref }} # release title
          body: 
          draft: false
          prerelease: false